/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniApp */

#ifndef _Included_JniApp
#define _Included_JniApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniApp
 * Method:    factorial
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JniApp_factorial
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
